# Generated by Django 4.2.1 on 2023-05-10 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cowName', models.CharField(max_length=45)),
                ('groupId', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='CowGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.IntegerField()),
                ('cowLandId', models.IntegerField()),
                ('cowGroupName', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='CowLand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cowLandName', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='CowLandUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cowLandId', models.IntegerField()),
                ('userId', models.IntegerField()),
                ('relation', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='CowState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cowId', models.IntegerField()),
                ('dateTime', models.DateTimeField()),
                ('cowState', models.IntegerField()),
                ('description', models.CharField(max_length=5000)),
            ],
        ),
        migrations.CreateModel(
            name='InputData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateTime', models.DateTimeField()),
                ('type', models.IntegerField()),
                ('sourceAddress', models.CharField(max_length=300)),
                ('cowId', models.IntegerField()),
                ('userId', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateTime', models.DateTimeField()),
                ('content', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='StateGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('groupId', models.IntegerField()),
                ('dateTime', models.DateTimeField()),
                ('groupState', models.IntegerField()),
                ('description', models.CharField(max_length=5000)),
            ],
        ),
        migrations.CreateModel(
            name='UserGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('groupId', models.IntegerField()),
                ('userId', models.IntegerField()),
                ('relation', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='UserNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userId', models.IntegerField()),
                ('notificationId', models.IntegerField()),
                ('state', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userName', models.CharField(max_length=45)),
                ('password', models.CharField(max_length=45)),
                ('access', models.CharField(max_length=45)),
            ],
        ),
    ]
