# Generated by Django 4.2.1 on 2024-02-17 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bcs', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserGroup',
        ),
        migrations.DeleteModel(
            name='Users',
        ),
    ]
